name: pdgrapher
channels:
  - conda-forge
  - conda-canary
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - cairo=1.16.0
  - certifi=2022.6.15
  - cycler=0.11.0
  - fftw=3.3.9
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.69.1
  - icu=67.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.15
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.21.5
  - olefile=0.46
  - openssl=1.1.1q
  - pcre=8.45
  - pixman=0.40.0
  - pycairo=1.19.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - rdkit=2020.09.5
  - readline=8.1.2
  - reportlab=3.5.68
  - six=1.16.0
  - sqlite=3.38.0
  - tk=8.6.11
  - tornado=6.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
